spring.application.name=LoginUsuario_AntonioBenitez

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/loginusuario
spring.datasource.username=${LOGINUSUARIO_USER}
spring.datasource.password=${LOGINUSUARIO_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

jwt.secret=${SECRET}
jwt.expiration=86400

server.port=443
server.ssl.key-store=keystore.p12
server.ssl.key-store-password=${HTTPS_PASSWORD}
server.ssl.keyStoreType=PKCS12
server.ssl.keyAlias=moka

springdoc.swagger-ui.path=/loginusuario.html
springdoc.api-docs.path=/loginusuario-docs