spring.application.name=CrudTabla_AntonioBenitez

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/crudtabla
spring.datasource.username=spring
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

springdoc.swagger-ui.path=/crudtabla.html
springdoc.api-docs.path=/crudtabla-docs